[colors]
foreground = "#e5ded6"
background = "#161c23"
cursor_bg = "#e5ded6"
cursor_border = "#e5ded6"
cursor_fg = "#161c23"
selection_bg = "#232d38"
selection_fg = "#e5ded6"

ansi = ["#12161C", "#d32c5d", "#5dd32c", "#dcb659", "#59c0dc", "${magenta}", "${cyan}", "${fg_dark}"]
brights = ["#13181E", "#d32c5d", "#5dd32c", "#dcb659", "#59c0dc", "${magenta}", "${cyan}", "#e5ded6"]
  